<a href="https://colab.research.google.com/github/ParasRajputt/Deep_Learning_Pytorch/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.11.0+cpu


In [11]:
#scalar
scalar = torch.tensor(5)
scalar

tensor(5)

In [12]:
scalar.ndim

0

In [13]:
#vector
vector = torch.tensor([4,5,6])
vector

tensor([4, 5, 6])

In [14]:
vector.ndim

1

In [18]:
vector.shape

torch.Size([3])

In [15]:
#MATRIX
MATRIX = torch.tensor([[1,2,3],[4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX.shape

torch.Size([2, 3])

In [24]:
#TENSOR
TENSOR= torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [25]:
TENSOR.ndim

3

In [26]:
TENSOR.shape

torch.Size([1, 3, 3])

# Random Tensors
### Why Random Tensor?
#### Neural Networks starts with a tensor with random numbers and learns by updating the random numbers again and again

In [30]:
random_tensor = torch.rand(1,4,5)
random_tensor, random_tensor.ndim , random_tensor.shape

(tensor([[[0.4113, 0.0392, 0.6284, 0.3741, 0.1450],
          [0.5482, 0.7420, 0.7862, 0.5138, 0.3713],
          [0.8578, 0.8796, 0.8990, 0.2018, 0.0341],
          [0.0542, 0.2630, 0.1367, 0.0158, 0.1650]]]),
 3,
 torch.Size([1, 4, 5]))

In [31]:
some_tensor = torch.rand(5,6)
some_tensor

tensor([[0.5764, 0.0268, 0.1949, 0.1476, 0.9614, 0.5291],
        [0.1969, 0.1523, 0.4304, 0.4553, 0.2961, 0.9442],
        [0.4153, 0.6226, 0.8155, 0.7855, 0.2557, 0.4121],
        [0.1568, 0.6080, 0.5879, 0.9516, 0.9831, 0.1377],
        [0.4285, 0.8053, 0.3746, 0.1401, 0.0804, 0.9512]])

In [36]:
print(f"Data type of tensor : {some_tensor.dtype}\n",
      f"Shape of tensor : {some_tensor.shape}\n",
      f"Device of tensor : {some_tensor.device}\n")

Data type of tensor : torch.float32
 Shape of tensor : torch.Size([5, 6])
 Device of tensor : cpu

