<a href="https://colab.research.google.com/github/ParasRajputt/Deep_Learning_Pytorch/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.11.0+cpu


In [2]:
#scalar
scalar = torch.tensor(5)
scalar

tensor(5)

In [3]:
scalar.ndim

0

In [4]:
#vector
vector = torch.tensor([4,5,6])
vector

tensor([4, 5, 6])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([3])

In [7]:
#MATRIX
MATRIX = torch.tensor([[1,2,3],[4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX.shape

torch.Size([2, 3])

In [10]:
#TENSOR
TENSOR= torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

# Random Tensors
### Why Random Tensor?
#### Neural Networks starts with a tensor with random numbers and learns by updating the random numbers again and again

In [13]:
random_tensor = torch.rand(1,4,5)
random_tensor, random_tensor.ndim , random_tensor.shape

(tensor([[[0.5425, 0.0889, 0.7605, 0.0063, 0.4776],
          [0.4388, 0.5725, 0.4773, 0.5878, 0.9392],
          [0.0681, 0.5907, 0.9769, 0.3807, 0.0349],
          [0.9716, 0.9951, 0.8294, 0.2710, 0.7084]]]),
 3,
 torch.Size([1, 4, 5]))

In [14]:
some_tensor = torch.rand(5,6)
some_tensor

tensor([[0.0853, 0.9217, 0.6466, 0.7412, 0.4847, 0.3371],
        [0.7651, 0.7945, 0.4889, 0.3420, 0.9568, 0.9074],
        [0.5065, 0.0961, 0.9240, 0.5069, 0.4456, 0.5845],
        [0.5055, 0.3678, 0.1982, 0.2620, 0.9285, 0.5646],
        [0.2549, 0.4152, 0.7653, 0.5560, 0.8685, 0.9182]])

In [15]:
print(f"Data type of tensor : {some_tensor.dtype}\n",
      f"Shape of tensor : {some_tensor.shape}\n",
      f"Device of tensor : {some_tensor.device}\n")

Data type of tensor : torch.float32
 Shape of tensor : torch.Size([5, 6])
 Device of tensor : cpu



Chapter 0 — Tensor Fundamentals: Notes



1.  ndim: nesting depth of a tensor (how many bracket levels before a raw number)

2.  shape: element count at each nesting level, outer→inner; len(shape) == ndim

3. Zero-init problem: all neurons get identical gradients → identical updates forever → network collapses to one effective neuron. Random init breaks symmetry.

4. float32 vs float16: float32 = default, more precision, more memory, slower. float16 = half memory, faster on Tensor Core GPUs (T4), but risks underflow on small values (e.g. small gradients rounding to 0). Mixed precision training uses float16 compute + float32 master weights to get both benefits.

5. matmul (2D): A(n×m) @ B(x×y) valid only if m==x; result shape (n×y). Each element = row·column dot product. 1D tensors matmul as a dot product (single scalar), not row/col rules.

6. reshape: total element count must match old and new shape. .view() requires contiguous memory and shares memory with original (no copy) — mutating one mutates the other. .reshape() uses view if possible, else copies.
squeeze/unsqueeze: remove/add size-1 dimensions to match shape expectations between tensors, ops, or models (e.g. adding a batch dim before feeding a single image to a model).

7. Indexing: x[row] = row, x[row,col] = element, x[:,col] = column.

8. NumPy interop: torch.from_numpy() / .numpy() share memory — same mutation risk as .view().

9. torch.manual_seed(n): fixes the RNG's starting point for the next call only, not permanently. Re-seed before each call if you need identical outputs from separate calls.










